### PR TITLE
Switch to Slash Commands

### PR DESCRIPTION
**Pull request by greysilly7**

### CODE REVIEW

**Comment by greysilly7** [comment]
@ChrisChrome this makes a few config changes so you might need to check that out

**Comment by TheArcaneBrony** [comment]
Concern: users who disable markdown preview (eg. me) cant use slash commands.

**Comment by greysilly7** [comment]
> Concern: users who disable markdown preview (eg. me) cant use slash commands.

What's markdown preview 👀 is that a **modded** client thing?

**Comment by greysilly7** [comment]
Also where is markdown used?

**Comment by TheArcaneBrony** [comment]
no, markdown preview is the thing that makes your text go bold etc in the input box. its a vanilla discord feature.

**Comment by TheArcaneBrony** [comment]
image

**Comment by greysilly7** [comment]
Honestly this is just copy and paste of commands essentially, so I don't really feel like changing formatting and then getting yelled at by @ChrisChrome

**Comment by ChrisChrome** [comment]
The implementation of slash commands is fine

**Comment by greysilly7** [comment]
> The implementation of slash commands is fine

Arcane is against slash commands because he doesn't wanna turn on markdown preview

**Pull request closed without merging**
